CREATE DATABASE RENAP;
USE RENAP;
CREATE TABLE PADRES (
    -> DPI VARCHAR(20) PRIMARY KEY,
    -> NOMBRE VARCHAR(50),
    -> PROFESION VARCHAR(20),
    -> ESTADO_CIVIL VARCHAR(20),
    -> NACIONALIDAD VARCHAR(20)
    -> );
    INSERT INTO PADRES (DPI, NOMBRE, PROFESION, ESTADO_CIVIL, NACIONALIDAD)
    -> VALUES ('1234567890101', 'Cuellar Solorzano', 'Ingeniero', 'Casado', 'Guatemalteco');
     select * from PADRES;

CREATE TABLE BEBE (
    -> CUI VARCHAR(20) PRIMARY KEY,
    -> NOMBRE_COMPLETO VARCHAR(50),
    -> FECHA_NACIMIENTO VARCHAR(20),
    -> LUGAR_NACIMINETO VARCHAR(20),
    -> NACIONALIDAD VARCHAR(20) FOREIGN KEY
    -> );
    INSERT INTO BEBE (CUI, NOMBRE_COMPLETO, FECHA_NACIMIENTO, LUGAR_NACIMINETO, NACIONALIDAD)
    -> VALUES ('3281946890101', 'Mateo Lara', '25/10/2006', 'Ciudad de Guatemala', 'Guatemalteco');
     select * from BEBE;