CREATE DATABASE RENAP;
USE RENAP;
CREATE TABLE PADRES (
    -> DPI VARCHAR(50) PRIMARY KEY,
    -> NOMBRE VARCHAR(50),
    -> PROFESION VARCHAR(20),
    -> ESTADO_CIVIL VARCHAR(20),
    -> NACIONALIDAD VARCHAR(20)
    -> );
    INSERT INTO PADRES (DPI, NOMBRE, PROFESION, ESTADO_CIVIL, NACIONALIDAD)
    -> VALUES ('1234567890101', 'Cuellar Solorzano', 'Ingeniero', 'Casado', 'Guatemalteco');
     select * from PADRES;